### ISSUE TITLE
Segmentatio fault

### ISSUE THREAD

**Issue by cayleyflyer** [lspr98/bike-computer-32#2]
HI
Many thanks for sharing your code
I have compiled the code using cmake which all went well ,  but when i run it  "./osm2simpletile east.pbf  mapeast.bin"
it runs through process 1/6 and 2/6 and stops at 3/6

I get a segmentation fault at 3/6

**------------------------- 3/6 Mapping highways to tiles ------------------------
Segmentation fault (core dumped**)

I got the fault on my lap top which has 8mb of ram and also on my desktop machine. which is also running Ubuntu 22.04, with 32mb of ram. Any suggestions would be appreciated.
regards
jez

**Comment by lspr98** [comment]
Hey jez,

I supposed you mean 8gb (or 32gb) of ram? Anyway, the segmentation fault is probably not due to insufficient RAM but rather a bug on my side. To help you, I would need two things from you:

1. Could you try it with a .osm.pbf file from [geofabrik](https://download.geofabrik.de/) ? Maybe they even offer the map that you are interested in. This is where I get my maps from and for example the [germany.osm.pbf](https://download.geofabrik.de/europe/germany-latest.osm.pbf) map conversion works fine for me.

2. Where did you get east.pbf from? I'd like to try it with your file too to see if I can reproduce the issue.

**Comment by cayleyflyer** [comment]
HI,
Thank you for your reply ,

Yes sorry, 8gb on laptop 32gb on desktop!

And yes I got my map from geofabrik .The file is in England named "east-yorkshire-with-hull-latest.osm.pbf" i just shortened it to 'east.pbf'  so i did not have to keep typing a long name.

OK I ran a .pbf file from geofabrik  named "bremen-latest.osm.pbf" and it worked  OK and created a bin file . I downloaded a fresh   "east-yorkshire-with-hull-latest.osm.pbf"  and it gives the Segmentation fault as described.

I ran the 'lincolnshire-latest.osm.pbf'  which crosses the '0' degree longitude and it also gives a segmentation error. Areas that do not bisect '0' degrees longitude ,either east or west work fine.

With the above result my feeling is,  because '0' degrees longitude runs through England in East Yorkshire. Everything to the East of me has a positive Longitude number  and everything West of my town has a negative longitude number. Therefore when  I run the  osm2simpletile  on a map that crosses '0' degrees longitude it gives A Segmentation error.

could this be the issue, the code handing negative longitude and positive longitude in the same file?

any suggestions would be most welcome

Kind regards
jez

**Comment by lspr98** [comment]
Hey Jez,

thanks for the hint with 0 longitude. The problem was indeed caused by negative longitude coordinates. I have updated the conversion tool, the python utilities and the esp firmware to support signed coordinates. Could you please pull again and let me know if it works for you?

There is still one catch though: the map may not render portions of streets when near the 0 longitude and/or 0 latitude mark. I'm unsure if this is caused by a bug or a design choice I made to reserve negative local tile coordinates to encode meta data later on. You can use the jupyter notebook test_plot_partial_map.ipynb to check it out for yourself.

**Comment by cayleyflyer** [comment]
HI,
Thank you 
Whatever you did has solved the issue and now the OSM.pbf files that bisect '0' degrees lon,  compile to a .bin file OK. 
For my flight instrument project I am aim to create a custom map showing Airspace restrictions with just main roads, railway lines and major landmarks, which can be seen from the air. so small streets will not be an issue.

many thanks for you help

Kind regards
Jez
