### ISSUE TITLE
map scale

### ISSUE THREAD

**Issue by cayleyflyer** [lspr98/bike-computer-32#3]
Hi,
I am using a 400 x 240 Sharp Memory LCD. I am trying to fill the screen with a map to show a larger area. I can change the RENDER_TILES_PER_DIM = 7 and DETAULT_ZOOM_LEVEL = 0.1 (in Globalconfig.h). this produces a map of the scale close to what I wish to have (see pic)
![lcd_map](https://github.com/lspr98/bike-computer-32/assets/77672808/fe061d69-d4a7-49db-8bf2-933b8f98bd56)

The map however does not fill the screen,  and  7 appears to be the max number I can  use in RENDER_TILES_PER_DIM.  If I enter 9 or 11 for example it will not render the tiles. I thought it may be due to the tile renderer buffer size. I noted the buffer size in tileblockrederer.cpp (_renderTileData = new int16_t[_perTileBufferSize * N_RENDER_TILES])  was an int16_t so I changed it to a int32_t but this had no effect.

Have you any ideas that could allow me zoom out and fill the screen to see more area. For my project  I need to see at least 6km in front of my GPS position and 2km each side of my GPS position.

kind regards
Jeremy

**Comment by lspr98** [comment]
Hey Jeremy,

my guess is that you are running out of RAM, which is why the map stops rendering if you go too high with **RENDER_TILES_PER_DIM**. From your picture, I see that you are using an ESP-WROOM-32, which comes with 520 kb of SRAM according to its datasheet. The size for **_renderTileData** is calculated based on the maximum number of nodes across all tiles in the map (**max_nodes** in header) and the number of tiles that are rendered (**N_RENDER_TILES**). The DACH map I am using has 4405 max_nodes, which means a 3 by 3 tile buffer requires 4405 * 2 * 3 * 3 ~ 80kb of RAM. A 7 by 7 buffer already requires ~431kb and a 9 by 9 buffer would require ~713kb, which exceeds that if your board. You can check the **max_nodes** value using the jupyter notebook **test_loading.ipynb** by printing the header dict after loading (in python, the value is called **max_tile_nodes**). 

The simplest solution would be to upgrade to an ESP with more RAM, but I do not recommend that, since the computational complexity for rendering the map rapidly increases for a large amount of tiles. If you are moving fast, it will also constantly have to reload a lot of tiles from the SD-Card, which creates stutter.

As an alternative, you could change the **tile_size** in **main.cpp** of the map conversion tool to a higher value, say 1024 (or higher) instead of 512. This will have the same effect as zooming out with a factor of 2. A **DETAULT_ZOOM_LEVEL = 1.0** means that the tile matches the display width defined in **DISPLAY_WIDTH**. To resolve the RAM issue, you will have to refine the filter in the map conversion tool (search for all occurances of "highway" in **CustomHandlers.hpp**), to exclude smaller ways and only keep major highways, which will reduce the maximum number of nodes on the tiles. For the zoom level that you request (6 by 2 km map on a 400 x 240 screen) this shouldn't really be an issue.

Also note that **Globalconfig.h** has two constants **DISPLAY_WIDTH** and **DISPLAY_HEIGHT** that you will need to adapt.

Just out of curiosity, does it render across the full screen when you set **DETAULT_ZOOM_LEVEL = 1.0** with **RENDER_TILES_PER_DIM = 7** ? Maybe there is also another issue with different screen aspect ratios.

**Comment by cayleyflyer** [comment]
Hi,
Thank you,
Your detailed reply has made it much easier to better understand the code.

Yes the the map did render across the full screen at Zoom level 1, however that map tile was a small size 513 nodes *2 *7 *7 = 50kb. My initial statergy was wrong, in trying to reduce the zoom size and increase the number of tiles to get the  6km x 4km view.  I want to make myself a paragliding instrument to show a moving map with airspace GPX overlay. I am not moving much faster than I would do on a bike. As you have kindly explained in your reply, Increasing tile size should be the way to go. 

After testing last night I created several maps at 1024,1800,1900,2048 tile size. I set zoom =1 and DIM = 3 . 
the max_nodes in each maptile set gave memory sizes 9kb,26kb,55,kb,64kb,72kb. However, only maps upto (1800) 55kb loaded and displayed correctly. I will need a tile size 4096 to achieve the zoom level I need. After some reading the ESP WROOM has 520kb of SRAM but it appears only 320kb of the 520kb SRAM is actually available which should be ok for me. Whatever is happening, I only appear to have a tiny amount (60kb) available to use. This would explain why the 1800 (55kb)tiles load and the 1900 (64kb)tiles do not. The module I am using is several years old so I have ordered a newer version ESP32 to rule out hardware issues. 

Again many thanks for your help
kind regards
Jeremy

**Comment by cayleyflyer** [comment]
A new ESP made no difference. So I kept the map tile size to 4096 in main.cpp and I filtered the large pbf file using OSMIUM to remove residential streets which reduced the max_nodes like this ,,,,, osmium tags-filter my.osm.pbf w/natural=water w/railway = rail w/railway=abandoned w/highway=motorway w/highway=trunk w/highway=primary w/highway=secondary w/highway=tertiary w/highway=unclassified  \-o reduced_node .pbf

The "reduced_node.pbf"  created a  map file  showing an area of 5.5km x 3.5km at zoom=1 and DIM=3 and kept the buffer to 38kb.
regards
Jeremy

**Comment by lspr98** [comment]
Hey Jeremy,

sorry for the delay. I did some tests with my ESP and have to admit a mistake in the formula for calculating the necessary memory, there is a factor of 2 missing, since each node consists of two 16bit signed integers (which means 4 bytes per node are required). The **_renderTileData** buffer is initialized via heap initialization, so it is possible to check the memory before and afterwards via `ESP.getFreeHeap()`. Here is the header of the map I'm using as read by the jupyter notebooks provided:
```
{
'map_x': 652675,
'map_y': 5982838,
'map_width': 1027954,
'map_height': 1390019,
'n_x_tiles': 2008,
'tile_size': 512,
'n_tiles': 5451720,
'max_tile_nodes': 2871,
'total_tile_nodes': 104140822,
'ways': 64903320
}
``` 

Calling the method mentioned above allows you to print out the available heap memory for the buffer before and after buffer allocation. I wrote some debug messages to check how much memory is actually allocated:
```
maxNodes: 2871, nRenderTiles: 9, perTileBufferSize: 5742, sizeof(int16_t): 2
Free heap before _renderTileData allocation: 265564 bytes
_renderTileData size: 103356 bytes
Free heap after _renderTileData allocation: 162192 bytes
```
So **max_nodes** * **N_RENDER_TILES** * **sizeof(int16_t)** * 2 is the actual size required in bytes. In my case, that is ~100kb for a 3x3 tile layout.

That means rendering a 5x5 tile layout is already out of scope:
```
maxNodes: 2871, nRenderTiles: 25, perTileBufferSize: 5742, sizeof(int16_t): 2
Free heap before _renderTileData allocation: 265308 bytes
_renderTileData size: 287100 bytes
# CRASH
```

The available heap can vary from board to board and also depends on the GPX track size if you are using that feature. I hope that helps clarify the memory issue. Still, changing the tile size and filtering out smaller streets is in my opinion the best solution. I interpret your last message that you were able to achieve your goal with the new filter? If so, please feel free to close the issue. Also, a picture of your bigger display rendering the map would be appreciated :)

**Comment by cayleyflyer** [comment]
![map4096](https://github.com/lspr98/bike-computer-32/assets/77672808/4dc4f894-eb6b-4eac-b963-d1c4b6358337)
hi, 
4096 map just the primary roads.
