### ISSUE TITLE
printing waypoint and place names

### ISSUE THREAD

**Issue by cayleyflyer** [lspr98/bike-computer-32#5]
`HI,`
I have managed to make an airspace map covering the whole of the uk at a scale of 3km x 5km on the screen at zoom level 1. I  have altered the GPXtrack entry to include a waypoint name. example trkpt lat="53.901000" lon="-0.171614" name= "wp1" . I can now display the points on the map. I also have  the coordinates of all uk towns and villages so I can show them on the map.

I am however having difficulty  printing the name from the GPX file on the screen next to the waypoint. 

I believe the TileBlockRenderer.cpp  and SharedSPISDCard.cpp are the blocks of code that read and render the GPXfile.
From within the function/method named void TileBlockRenderer::renderGPX(LocalGeoPosition& center). I have tried to use  _display->write1 () with some success (i copied display.write it and changed its paramiters to 'char'. In doing so I can  print  on the screen,but only one letter of the waypoint array (see picture below).  I am having difficulty in finding a way to get all the characters in the waypoint name into one array and to print it on the screen. I can create  a char*wplist for each letter in the name and do it that way but that seems wrong to me to do that.

 the altered the GPXtrack.h as below to include a variable to hold the waypoint name letters.
/*
    GPX-Track
*/
struct GPXTrack {
public:
    int16_t* xList;
    int16_t* yList;
    char* wplist; //char* wplist works,  char*wplist[8] and char wplist does not work
    char* wplist1; //char* wplist1 works,  char*wplist[8] and char wplist does not work
    char* wplist2; //char* wplist2 works,  char*wplist[8] and char wplist does not work
    uint64_t* tileIdList;
    uint32_t numNodes;
    uint32_t nearestNodeId;
};

inside this code block:-
bool SharedSPISDCard::readGPX(SimpleTile::Header& header, GPXTrack& track) {

I have added 
  // Allocate memory for track data for each letter in name
track.wplist = new char[n_nodes]; // not sure if this makes any difference
track.wplist1 = new char[n_nodes]; // not sure if this makes any difference
track.wplist2 = new char[n_nodes]; // not sure if this makes any difference

I have added,  ptr_wp_start and ptr_wp_end routines which follow the format for lat and lon routines including, ptr_wp_start = line.indexOf("name") + 6; to extract the waypoint name.

I have converted the waypoint String from above to a null terminated char array called 'wpo' using toCharArray() 
           
below is an extract from the serial monitor showing I have successfully parsed the GPXfile and placed the waypoint name into a char array called 'wpo'
      sout << " lat " << lat <= "  ";
      sout << " lon " << lon <= "  ";
      sout << "name " << wpo <= " ";    ) 

Free heap before GPX: 296656
Free heap after GPX: 296512
 lat 53.90  
 lon -0.17  
name ap1 
 lat 53.91  
 lon -0.17  
name bp2 

I only seem to able to pass one letter in the waypoint into _track.wplist[i]
In tileblockrenderer.cpp, therefore I have added a line for each letter in wp name which works!.
         char wp = _track->wplist[nidx];
         char wp1 = _track->wplist1[nidx];
         char wp2 = _track->wplist2[nidx];

I have using this method successfully printed the waypoint name on the screen next to the waypoint marker, but I have been unable to concaternate all the letters into one array and print the full name. So an 8 letter name required 8 lines of code

I think I am missing some knowledge, about how to pass the whole waypoint name in one variable and into the 'wplist' and print it. 

Any advice on how I could achieve printing the name to the screen  would be welcome. ?

kind regards
Jeremy

![map](https://github.com/user-attachments/assets/0ab4bbfc-bfab-43f7-903b-163916717fa2)

**Comment by lspr98** [comment]
Hey Jeremy,

if I understand your issue correctly, you are trying to provide waypoint names through the GPX file and display them on the screen. I am unsure which changes you made in the code and to help you resolve your issue it would be great if you could post your code changes as a public fork of this repository, so I can have a look at it.

I tried to sketch some code for you with the way I interpret how you are trying to solve the problem. It is a sketch though, no guarantee if it works, I haven't tested it:

1. Extend the GPXTrack with a new field `nameList` which will hold all waypoint names. 
```
struct GPXTrack {
public:
    int16_t* xList;
    int16_t* yList;
    char** nameList;
    uint64_t* tileIdList;
    uint32_t numNodes;
    uint32_t nearestNodeId;
};
```
Note that `nameList` is a "pointer to a pointer", since we need a 2D `char` array to hold the chars for each name for each waypoint.

2. In `SharedSPISDCard::readGPX` after the first pass through the GPX file, we know the number of waypoints (`n_nodes`) which we can use to allocate the first dimension of the `nameList`:
```
track.tileIdList = new uint64_t[n_nodes];
track.xList = new int16_t[n_nodes];
track.yList = new int16_t[n_nodes];
track.nameList = new char*[n_nodes];
```
Again, `nameList` is an array of `char*`, each element of `nameList` will point to the first character of a waypoint name.

3. In `SharedSPISDCard::readGPX` during the second pass through the GPX file, find the start and end pointers to the waypoint name:
```
ptr_name_start = line.indexOf("name") + 6;
ptr_name_end = ptr_name_start;
while(line.c_str()[ptr_name_start] != '\"') {
    ptr_name_end++;
    if(ptr_name_end == line.length()) {
        sout.err() <= "Failed to read NAME for GPX track";
        return false;
    }
}
```
`ptr_name_start` will be the character offset to the first waypoint name character, while `ptr_name_end` will be the offset to the last waypoint name character.

4. In `SharedSPISDCard::readGPX`, allocate space for the current waypoint name and copy it from the GPX-file string:
```
uint16_t nameLength = ptr_name_end - ptr_name_start;
// Allocate space for the i-th waypoint name. We need one additional character for null-termination
track.nameList[i] = new char[nameLength + 1];
memcpy(track.nameList[i], &(line.c_str()[ptr_name_start]), nameLength * sizeof(char));
// Add null termination at end of waypoint name
track.nameList[i][nameLength + 1] = '\0';
```

After that, `track.nameList[i]` gives you the i-th null-terminated waypoint name, which you can pass to your function for showing the names on the display.

I am however not planning on implementing this feature, so you will be on your own for that.

**Comment by cayleyflyer** [comment]
many thanks,
The code you kindly provided has worked. The map resolution here is 30km x 20km. A gpx  file with1250 placenames/waypoints loaded ok 
I clearly  have a bit to learn about pointers. and pointer to pointers!
kind regards
jeremy

![airmap](https://github.com/user-attachments/assets/4798f3ba-e604-46b2-b578-7f517b74a898)

**Comment by cayleyflyer** [comment]
thanks
